Repository vJechsmayr/PythonAlgorithms, pull requests merged in 2020-10, with the labels that each got.

#43 Implemented Merge Two Sorted Lists
  LeetCode/0021_Merge_Two_Sorted_Lists.py
Labels: Correct-Solution

#49 Added 3sum
  LeetCode/0015_3Sum.py
  LeetCode/0043_Multiply Strings.py
  LeetCode/0081_Search_in_Rotated_Sorted_Array II.py
Labels: Changes-Requested, invalid

#190 0076_Minimum_Window_Substring
  LeetCode/0076_Minimum_Window_Substring.py
Labels: Changes-Requested

#272 0532_K-diff_Pairs_in_an_Array.py
  LeetCode/0523_K_diff_Pairs_in_an_Array.py
  LeetCode/1288_Remove_Covered_Intervals.py
Labels: Changes-Requested

#403 Added 0268_Missing_Number.py
  LeetCode/0268_Missing_Number.py
Labels: Changes-Requested

#501 Added 0257_Binary_Tree_Paths.py
  LeetCode/0257_Binary_Tree_Paths.py
Labels: Changes-Requested

#531 Add 1499. Max Value of Equation
  LeetCode/1499_Max_Value_of_Equation.py
Labels: Changes-Requested

#543 Add 1340. Jump Game V
  LeetCode/1340_Jump_Game_V.py
Labels: Changes-Requested

#554 Create 1589-maximum-sum-obtained-of-any-permutation.py
  LeetCode/1589-maximum-sum-obtained-of-any-permutation.py
Labels: Changes-Requested

#559 added solution to leetcode problem 1346
  LeetCode/1346_Check_if_N_and_its_Double_Exist.py
Labels: Changes-Requested

#276 Added Minimum_Number_of_K_Consecutive_Bit_Flips
  LeetCode/0995_Minimum_Number_of_K_Consecutive_Bit_Flips.py
Labels: hacktoberfest-accepted
